<a href="https://colab.research.google.com/github/lewinskie254/eda/blob/main/Anova_Link_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import statistics as stat
import scipy.stats as stats

In [116]:
#one way anova is categorical to numeric relationships
df = pd.read_csv("http://ishelp.info/data/bikebuyers.csv")

In [108]:
from scipy.stats import f

#anova the heck outta this
#first the f statistic

# number of predictors
k = 2
n = len(df)

# degrees of freedom
dfn = k
dfd = n - k - 1

# F critical at 95% confidence
f_critical = f.ppf(0.95, dfn, dfd)
print("F-critical:", f_critical)
df.columns

F-critical: 3.004751748095738


Index(['ID', 'Marital Status', 'Gender', 'MaritalStatusNumeric',
       'GenderNumeric', 'Income', 'Children', 'EducationNumeric',
       'CommuteDistanceNumeric', 'Cars', 'Age', 'HomeOwnerNumeric',
       'PurchaseBikeNumeric', 'Education', 'Occupation', 'Home Owner',
       'Commute Distance', 'Region', 'Purchased Bike'],
      dtype='object')

In [109]:
from scipy.stats import f_oneway

#one way anova
f, p = f_oneway(df['Income'], df['EducationNumeric'])
f

np.float64(3262.0183077262877)

In [117]:
df['Education'].unique()

array(['Bachelors', 'Graduate Degree', 'High School', 'Partial College',
       'Partial High School'], dtype=object)

In [118]:
df['EducationNumeric'] = df['Education']

df.EducationNumeric.replace(
    ['Bachelors', 'Graduate Degree', 'High School', 'Partial College',
       'Partial High School'],
    [1, 2, 3, 4, 5],
    inplace=True
)

/tmp/ipython-input-2500618915.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.EducationNumeric.replace(
/tmp/ipython-input-2500618915.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.EducationNumeric.replace(


In [119]:
df.EducationNumeric.unique()

array([1, 2, 3, 4, 5])

995    5
996    5
997    5
998    5
999    5
Name: EducationNumeric, dtype: int64

In [121]:
df.columns

Index(['ID', 'Marital Status', 'Gender', 'MaritalStatusNumeric',
       'GenderNumeric', 'Income', 'Children', 'EducationNumeric',
       'CommuteDistanceNumeric', 'Cars', 'Age', 'HomeOwnerNumeric',
       'PurchaseBikeNumeric', 'Education', 'Occupation', 'Home Owner',
       'Commute Distance', 'Region', 'Purchased Bike'],
      dtype='object')

In [122]:
df.CommuteDistanceNumeric.unique()

array([1, 5, 2, 3, 4])

In [128]:
df['Commute_rank'] = df['Commute Distance'].replace(
    ['0-1 Miles', '1-2 Miles', '2-5 Miles', '5-10 Miles', '10+ Miles'],
    [0, 1, 2, 5, 10]
)

/tmp/ipython-input-2173514330.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Commute_rank'] = df['Commute Distance'].replace(


In [129]:
df.Commute_rank.unique()

array([ 0, 10,  1,  2,  5])